# Generated by Django 4.2.4 on 2023-08-20 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myApp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=myApp.models.get_blog_uuid, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('category', models.CharField(choices=[('mental_health', 'mental_health'), ('nutrition', 'nutrition'), ('healthy_diet', 'healthy_diet'), ('obesity', 'obesity')], max_length=100)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
