# Generated by Django 4.2.4 on 2023-08-20 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_blog_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 8, 20, 15, 45, 30, 435448)),
            preserve_default=False,
        ),
    ]
